address/urls.py
from django.urls import path, re_path
from address.views import AddressView, AddressViewDK
from django.contrib import admin

app_name = 'address'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', AddressView.as_view(), name='address'),
    path('<int:pk>/', AddressViewDK.as_view(), name='detail'),
]

blog/urls.py
from django.urls import path, re_path
from blog.views import BlogView
from django.contrib import admin

app_name = 'blog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', BlogView.as_view(), name='blog'),
]

board/urls.py
from django.urls import path, re_path
from board.views import *
from django.contrib import admin

app_name = 'board'

urlpatterns = [
    path('', BoardView.as_view(), name='board'),
    path('<int:pk>', BoardViewDV.as_view(), name='details'),
    # Example: /board/add
    path('add/', BoardCreateView.as_view(), name="add"),
    # Example: /bookmark/change/
    # path('change/', BoardChange.as_view(), name="change"),
    # # Example: /bookmark/99/update/
    path('<int:pk>/update/', BoardUpdateView.as_view(), name="update"),
    # Example: /bookmark/99/delete/
    path('<int:pk>/delete/', BoardDeleteView.as_view(), name="delete"),
]

owner/urls.py
from django.contrib import admin
from django.urls import path, include
from owner.views import HomeView
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
    path('address/', include('address.urls')),
    path('board/', include('board.urls')),
]

address/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Information(models.Model):
    name = models.CharField(max_length=50, blank=True)
    address = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name

blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse

class BlogBoard(models.Model):
    title = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.title

board/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils.text import slugify



from taggit.managers import TaggableManager

class BoardLI(models.Model):
    name = models.CharField('NAME', max_length=100)
    title = models.CharField('TITLE', max_length=50, blank=True)
    content = models.TextField('CONTENT')

    def __str__(self):
        return self.title


class Meta:
    verbose_name = 'post'
    verbose_name_plural = 'posts'
    db_table = 'board_posts'
    ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

address/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from address.models import Information

# TemplateView
class AddressView(ListView):
    template_name = 'information.html'
    model = Information

class AddressViewDK(DetailView):
    template_name = 'address_detail.html'
    model = Information
    context_object_name = 'detail'

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from blog.models import BlogBoard

# TemplateView
class BlogView(ListView):
    template_name = 'post.html'
    model = BlogBoard

board/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from board.models import BoardLI, models
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, \
    TodayArchiveView
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


# TemplateView
class BoardView(ListView):
    template_name = 'board_list.html'
    model = BoardLI
    context_object_name = "boards"
    paginate_by = 10


class BoardViewDV(DetailView):
    template_name = 'board_detail.html'
    model = BoardLI
    context_object_name = 'details'


class BoardCreateView(CreateView):
    model = BoardLI
    template_name = 'board_form.html'
    fields = ['name', 'title', 'content']
    # initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('board:board')

    def form_valid(self, form):
        return super().form_valid(form)


class BoardUpdateView(UpdateView):
    model = BoardLI
    fields = ['name', 'title', 'content']  # 폼 모델에 사용할 필드  폼 모델 자동 생성
    success_url = reverse_lazy('board:board')
    template_name = 'board_form.html'


class BoardDeleteView(DeleteView):
    model = BoardLI
    success_url = reverse_lazy('board:board')
    template_name = 'board_delete.html'


# class BoardChangeLV(LoginRequiredMixin, ListView):
#     template_name = 'board/board_change_list.html'
#     def get_queryset(self):
#         return Board.objects.filter(owner=self.request.user)

owner/views.py
from django.views.generic import TemplateView
from django.shortcuts import render

# TemplateView
class HomeView(TemplateView):
    template_name = 'index.html'

address/templates/address_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>상세주소록</h2>
<br>
<li> URL : <a href ="#">{{detail.name}}</a></li>
</body>
</html>

address/templates/information.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>주소록입니다.</h2>
{% for address in object_list %}
<li>
    <a href="{% url 'address:detail' address.id %}">{{ address.name }}</a>
</li>
{% endfor %}
</body>
</html>

blog/templates/post.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>블로그입니다.</h2>
{% for bookmark in object_list %}
<li>
    {{ bookmark.title }}
</li>
{% endfor %}
</body>
</html>

board/templates/Board/Board_archive.html
<h1>Post Archives until {% now "b d, Y" %}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'Board:Board_year_archive' date|date:'Y' %}">
            Year-{{ date|date:"Y" }}</a></li>
    {% endfor %}
</ul>
<br/>
<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ Board.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

board/templates/Board/Board_archive_day.html
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

board/templates/Board/Board_archive_month.html
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>
<div>
    <ul> {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

board/templates/Board/Board_archive_year.html
<h1>Board Archives for {{ year|date:"Y" }}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'Board:Board_month_archive'year|date:'Y' date|date:'m' %}">{{ date|date:"F" }}</a></li>
    {% endfor %}
</ul>
<br>
<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ Board.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

board/templates/board_confirm_delete.html
<h1>Bookmark Delete</h1>
<br>
<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
</form>
</div>
{% endblock %}

board/templates/board_delete.html
{% block title %}post_confirm_delete.html{% endblock %}
{% block content %}
 <h1>Post Delete</h1>
 <br>
 <form action="." method="post">{% csrf_token %}
 <p>Are you sure you want to delete "{{ object }}" ?</p>
 <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
 </form>
{% endblock %}

board/templates/board_detail.html
 <h1>제목 : {{details.title}}</h1>

 <h3>작성자 :{{object.name}}</h3>
 <p>
     {{object.content}}
 </p>

<a href="{% url 'board:board' %}"><button>목록보기</button></a>
<a href="{% url 'board:update' details.id %}"><i class='far fa-edit'></i><button>수정</button></a>
<a href="{% url 'board:delete' details.id %}"><i class='far fa-trash'></i><button>삭제</button></a>

board/templates/board_form.html
{% block title %}bookmark_form.html{% endblock %}
{% block content %}
<h1>Bookmark Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your bookmark.</p>
{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">
        Wrong! Please correct the error(s) below.
    </div>
    {{ form.errors }}
</div>
{% endif %}



<form action="." method="post" class="card pt-3">{% csrf_token %}
    <div class="form-group row">
       이름 : {{ form.name }}

        </div>
    </div>
    <div class="form-group row">
       제목 : {{ form.title }}

        </div>
    </div>

    <div class="col-sm-10">
       내용 : {{ form.content }}
    </div>
    <input type="submit">

</form>
{% endblock %}

board/templates/board_list.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>게시판</title>
</head>
<body>
<h2>게 시 판</h2>
<br>
<table>
    <thead>
    <tr>
        <td>이름</td>
        <td>제목</td>
        <td>내용</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        {% for board in object_list %}
        <td><a href="{% url 'board:details' board.id%}">{{board.name}}</a></td>
        <td><a href="{% url 'board:details' board.id%}">{{board.title}}</a></td>
        <td><a href="{% url 'board:details' board.id%}">{{board.content}}</a></td>
    </tr>
{% endfor %}

    </tbody>
</table>
<a href="{% url 'board:add' %}"><button>글쓰기</button></a>
</body>
</html>

templates/index.html
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>직접 만든 블로그</title>
</head>
<body>
    <h2>홈페이지입니다.</h2>
    <a href="{% url 'blog:blog' %}"><button>blog</button></a>
    <a href="{% url 'address:address' %}"><button>address</button></a>
    <a href="{% url 'board:board' %}"><button>board</button></a>
</body>
</html>